config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "home#index"

  get '/'=>'home#index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  

  resource :contacts, only: [:new, :create], path_names:{:new => ''}

  resources :articles do #REST
    resources :comments, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    #dependent: :destroy #Удаление связанных объектов (из бд Comment)
    
    validates :title, presence: true
    validates :text, presence: true

    def subject
      title
    end

    def last_comment
      comments.last
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessible :username       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Если это devise_controller? то будет выполнен before_filter :authenticate_user!,
  #(где у нас работает devise) и configure_permitted_parameters
  # В Rails 4 before_filter заменили на before_action 
  before_filter :configure_permitted_parameters, if: :devise_controller?

  #protected
  private
  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :username
     #devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     #devise_parameter_sanitizer.for(:sign_in) << :username
     #devise_parameter_sanitizer.for(:account_update) << :username
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController   
   before_filter :authenticate_user!, :only => [:new ,:create]
   #before_filter :authenticate_user!, except => [:show, :index]
   #before_action :authenticate_user!
   #before_action :authenticate_member!

   def index
    @articles = Article.all
   end

   def show
    @article = Article.find(params[:id])
   end

   def new
     @article = Article.new
   end

   def create
    #render plain: params[:article].inspect
      @article = Article.new(article_params)
      @article.author = current_user.username

      if @article.save
        redirect_to @article
      else
        render action: 'new'
      end
   end

   def edit
      @article = Article.find(params[:id])
   end

   def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
        redirect_to @article
      else
        render action: 'edit'
      end
   end

   def destroy
     @article = Article.find(params[:id])
     @article.destroy
 
     redirect_to articles_path 
   end

    private

    def article_params
      params.require(:article).permit(:title, :text)
      # :article - Имя хеша, :title, :text - ключи хеша
      # Написано верни хеш по имени :article, и значения с ключами :title, :text ,остальное не надо
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    #@comment = @article.comments.create(comment_params)

    @comment = @article.comments.new(comment_params)
    @comment.commenter = current_user.username
    @comment.save

    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
    end

    def create
      @contact = Contact.new(contact_params)
      if @contact.valid?
        @contact.save
      else
        render action: 'new'
      end
      
    end

 private
    def contact_params
      params.require(:contact).permit(:email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def terms
    end

    def about
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Articles</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
<p>
   <%= f.label :title %><br/>
   <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br/>
  <%= f.text_area :text %>
</p>

<%= f.submit %>

<% end %>

app/views/articles/index.html.erb
<h1>Index Articles</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<p><%= link_to 'New article', new_article_path %> </p> 

<% @articles.each do |article| %>
	 <h2><%= article.title %></h2>
	 <p>
	  <i>Create <%= article.author %> at <%= article.created_at %></i>
     </p>

	 <p>
	 <%= article.text %>
	 </p>

	 <p>
	 	<%= link_to 'Snow', article_path(article) %>
	    <% if user_signed_in? %>
		<% if article.author == current_user.username %>|		   
		   <%= link_to 'Edit', edit_article_path(article) %> |
		   <%= link_to 'Delete', article_path(article),
	                             method: :delete,
	                             data: { confirm: 'Are you sure?' } %>
	    <% end %>
	    <% end %>                         
	 </p>
	 <hr/>	 

<% end %>

app/views/articles/new.html.erb
<h1>New Articles</h1>

<%= form_for :article, url: articles_path do |f| %>

<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<p>
   <%= f.label :title %><br/>
   <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br/>
  <%= f.text_area :text %>
</p>

<%= f.submit %>

<% end %>

<p><%= link_to 'Back', articles_path %></p>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.text %></p>

<p><%= link_to 'Back', articles_path %></p>

<h2>Comments</h2>

<% @article.comments.each do |comment| %>
	 <h2><i><%= comment.commenter %></i></h2>	 
	 <p><%= comment.body %></p>
	 
	 <hr/>	 
<% end %>


<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/contacts/create.html.erb
<h1>Crete Contacts</h1>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
		 <li> <%= msg %> </li>
		<% end %>
		</ul>
	</p>
	<% end %>

	<p>
	   <%= f.label :email %><br/>
	   <%= f.text_field :email %>
	</p>

	<p>
	  <%= f.label :message %><br/>
	  <%= f.text_area :message %>
	</p>

	<%= f.submit 'Send message'%>

<% end %>

app/views/home/index.html.erb
<h1>Home#index2112</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'My Blog', articles_path %> |
<%= link_to 'Terms', terms_path %> |
<%= link_to 'About', about_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
	  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>


<div class="container">
			<!-- Static navbar -->
			<nav class="navbar navbar-default" role="navigation">
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="/">Blog</a>
			  </div>
			  <div class="navbar-collapse collapse">
			    <ul class="nav navbar-nav">
			      <li><%= link_to 'My Blog', articles_path %></li>
			      <li><%= link_to 'About', about_path %></li>
			      <li><%= link_to 'Terms', terms_path %></li>
			      <li><a href="/contacts">Contacts</a></li>
			    </ul>

			    <ul class="nav navbar-nav navbar-right">
			    			      
			      	 <% if user_signed_in? %>
			      	    <% welcome_username = 'Hi, ' + current_user.username+'!' %>
			      	    <li><div class="hidden-xs" style="margin-top: 15px"><%= welcome_username %></div></li>
			      	    <li><div class="hidden-xs" style="margin-top: 15px"><%= t('hello') %></div></li>
					    
					    <li><%= link_to 'Sing out', destroy_user_session_path, method: :delete %></li>		
					 <% else %>
						<li><%= link_to 'Sing in', new_user_session_path %></li>	 
					 <% end %>
			      
			    </ul>
			  </div><!--/.nav-collapse -->
			</nav>

	 <% if user_signed_in? %>
		Hello, <%= current_user.username %> | <%= link_to 'Sing out', destroy_user_session_path, method: :delete %>		
	 <% else %>
		<%= link_to 'Sing in', new_user_session_path %>	 
	 <% end %>

	 <p class="notice"><%= notice %></p>
	 <p class="alert"><%= alert %></p>

   <div> 
	  <%= yield %>
   </div>

   <div class="footer">
        <p>&copy; Company 2015</p>
   </div>
</div> <!-- /container -->
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
 xbfffffsh hrssshfhs
</p>

app/views/pages/terms.html.erb
<h1>Terms of Service</h1>
<p>
 xbfffffsh hrssshfhs
</p>